### ISSUE TITLE
Profile, add, gambling command

### ISSUE THREAD

**Issue by Cyberkingcr7** [Synthesized-Infinity/Whatsapp-Botto-Xre#23]
Hi please add a profile command, also adding a user to a group and lastly gambling with fake money

**Comment by AlenSaito1** [comment]
We'll not be adding any commands which will add people to group chats as the ban-risk is high. I've added the `profile` command in the commit [70fdae0](https://github.com/Synthesized-Infinity/Whatsapp-Botto-Xre/commit/70fdae0b821b31bccabce215ade2472878ba9e6c)
