### ISSUE TITLE
Add slap, pat and  punch 

### ISSUE THREAD

**Issue by rdrew-a6** [Synthesized-Infinity/Whatsapp-Botto-Xre#29]
Giving thanks to our simps Ban Takahiro

**Comment by SomnathDas** [comment]
@rdrew-a6  Done!

Main function
https://github.com/Synthesized-Infinity/Whatsapp-Botto-Xre/blob/1a9c24059eeede46b1d8f07031cb1de370146df9/src/lib/getGify.ts
