### ISSUE TITLE
Fuck the creator ban Takahiro and prajjwal neko too eat my dick

### ISSUE THREAD

**Issue by rdrew-a6** [Synthesized-Infinity/Whatsapp-Botto-Xre#31]

**Comment by SheIITear** [comment]
Chill, getting that butthurt might be too much for your big brain.

**Comment by AB1RZ9** [comment]
Well bruh seems like you're a experienced cumnt, well i got a offer for ya...Just behind my Residence, a few metres away is what you can call "red light district". It's infamous here and I've heard the h*es do earn a decent pay and get the best of D's. So why don't join?
