### ISSUE TITLE
Please Add Few Commands

### ISSUE THREAD

**Issue by jacktheboss220** [Synthesized-Infinity/Whatsapp-Botto-Xre#36]
Hey I'm using your bot for quite few times. I love it.
Can you please add few commands like:-
tts 
few fun commands
I hope you think about it.
Thanks 😊

**Comment by SomnathDas** [comment]
@jacktheboss220  Done!

Function Added:
https://github.com/Synthesized-Infinity/Whatsapp-Botto-Xre/blob/1a9c24059eeede46b1d8f07031cb1de370146df9/src/lib/getGify.ts

Commands Added: 
[prefix] slap
[prefix] punch
[prefix] pat

**Comment by Destiny-cpu** [comment]
@jacktheboss220 yh they should add that
