### ISSUE TITLE
Group chat link reset

### ISSUE THREAD

**Issue by Destiny-cpu** [Synthesized-Infinity/Whatsapp-Botto-Xre#42]
I know it's kinda wierd to ask this here but
Can I get the group chat link of xrex bot
It's a really cool bot
Or you can add my number instead please http://WA.me/+56921707411

**Comment by PabloChocobar69** [comment]
Add me too if possible! 

gg.gg/Ankan-Mitra

**Comment by SomnathDas** [comment]
Fixed
