### ISSUE TITLE
Yt error

### ISSUE THREAD

**Issue by NickoRey7** [Synthesized-Infinity/Whatsapp-Botto-Xre#46]
some Yt video and audio shows error.

**Comment by SomnathDas** [comment]
Elaborate your issue, please

**Comment by rimuru-sama3** [comment]
Error 429

**Comment by LuanRT** [comment]
This is YouTube rate limiting system, if you start getting status code 429 it means you've been making too many requests from the same IP address.

A way to mitigate this problem would be using cookies, but even that doesn't always work.
